sonata_admin:
    title: 'Minimization URL'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left, }
        groups:
            admin.clicks:
              label: Configuration
              icon: '<i class="fa fa-picture-o"></i>'
              item:
                - admin.clicks
                - admin.url_record


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
